# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.energy_flow_data_api import EnergyFlowDataApi  # noqa: E501


class TestEnergyFlowDataApi(unittest.TestCase):
    """EnergyFlowDataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EnergyFlowDataApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_energy_flow_data(self) -> None:
        """Test case for get_energy_flow_data

        Get Energy Flow Data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
