# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_events200_response import GetEvents200Response  # noqa: E501

class TestGetEvents200Response(unittest.TestCase):
    """GetEvents200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEvents200Response:
        """Test GetEvents200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEvents200Response`
        """
        model = GetEvents200Response()  # noqa: E501
        if include_optional:
            return GetEvents200Response(
                data = [{"event":"BMS Discharger Over Current","start_time":"2003-07-03T06:06:16Z","end_time":null},{"event":"GFCI Fault","start_time":"2013-01-28T05:52:01Z","end_time":null}]
            )
        else:
            return GetEvents200Response(
        )
        """

    def testGetEvents200Response(self):
        """Test GetEvents200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
