# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_data_points200_response_data_inner_power_battery import GetDataPoints200ResponseDataInnerPowerBattery  # noqa: E501

class TestGetDataPoints200ResponseDataInnerPowerBattery(unittest.TestCase):
    """GetDataPoints200ResponseDataInnerPowerBattery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDataPoints200ResponseDataInnerPowerBattery:
        """Test GetDataPoints200ResponseDataInnerPowerBattery
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDataPoints200ResponseDataInnerPowerBattery`
        """
        model = GetDataPoints200ResponseDataInnerPowerBattery()  # noqa: E501
        if include_optional:
            return GetDataPoints200ResponseDataInnerPowerBattery(
                percent = 79,
                power = -2289,
                temperature = 12
            )
        else:
            return GetDataPoints200ResponseDataInnerPowerBattery(
        )
        """

    def testGetDataPoints200ResponseDataInnerPowerBattery(self):
        """Test GetDataPoints200ResponseDataInnerPowerBattery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
