# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.create_smart_device_data_point200_response import CreateSmartDeviceDataPoint200Response  # noqa: E501

class TestCreateSmartDeviceDataPoint200Response(unittest.TestCase):
    """CreateSmartDeviceDataPoint200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateSmartDeviceDataPoint200Response:
        """Test CreateSmartDeviceDataPoint200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateSmartDeviceDataPoint200Response`
        """
        model = CreateSmartDeviceDataPoint200Response()  # noqa: E501
        if include_optional:
            return CreateSmartDeviceDataPoint200Response(
                data = [{"time":"1980-01-20T17:51:33Z","power":622},{"time":"1971-05-31T19:34:47Z","power":567}]
            )
        else:
            return CreateSmartDeviceDataPoint200Response(
        )
        """

    def testCreateSmartDeviceDataPoint200Response(self):
        """Test CreateSmartDeviceDataPoint200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
