# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.send_command200_response import SendCommand200Response  # noqa: E501

class TestSendCommand200Response(unittest.TestCase):
    """SendCommand200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendCommand200Response:
        """Test SendCommand200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendCommand200Response`
        """
        model = SendCommand200Response()  # noqa: E501
        if include_optional:
            return SendCommand200Response(
                data = openapi_client.models.send_command_200_response_data.sendCommand_200_response_data(
                    code = 0, 
                    success = True, 
                    message = 'Accepted', )
            )
        else:
            return SendCommand200Response(
        )
        """

    def testSendCommand200Response(self):
        """Test SendCommand200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
