# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_your_account_children_information200_response import GetYourAccountChildrenInformation200Response  # noqa: E501

class TestGetYourAccountChildrenInformation200Response(unittest.TestCase):
    """GetYourAccountChildrenInformation200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetYourAccountChildrenInformation200Response:
        """Test GetYourAccountChildrenInformation200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetYourAccountChildrenInformation200Response`
        """
        model = GetYourAccountChildrenInformation200Response()  # noqa: E501
        if include_optional:
            return GetYourAccountChildrenInformation200Response(
                data = [{"id":13,"name":"wright.dylan","role":"ADMIN","email":"maisie88@gmail.com","address":"48 Anderson Square","postcode":"NR31 8NS","country":"NORTH_KOREA","telephone_number":"06063 382394","timezone":"GMT -3"},{"id":14,"name":"julie.richardson","role":"EXTERNAL","email":"samantha56@hotmail.com","address":"3 Grace Ferry","postcode":"SE18 7QX","country":"SRI_LANKA","telephone_number":"+44(0)9295459343","timezone":"GMT +12"}]
            )
        else:
            return GetYourAccountChildrenInformation200Response(
        )
        """

    def testGetYourAccountChildrenInformation200Response(self):
        """Test GetYourAccountChildrenInformation200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
