# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.communication_device_api import CommunicationDeviceApi  # noqa: E501


class TestCommunicationDeviceApi(unittest.TestCase):
    """CommunicationDeviceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CommunicationDeviceApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_communication_device_information_by_serial_number(self) -> None:
        """Test case for get_communication_device_information_by_serial_number

        Get Communication Device Information by Serial Number  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
