# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_account_dongles_by_id200_response_data_inner_inverter_info import GetAccountDonglesByID200ResponseDataInnerInverterInfo  # noqa: E501

class TestGetAccountDonglesByID200ResponseDataInnerInverterInfo(unittest.TestCase):
    """GetAccountDonglesByID200ResponseDataInnerInverterInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAccountDonglesByID200ResponseDataInnerInverterInfo:
        """Test GetAccountDonglesByID200ResponseDataInnerInverterInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAccountDonglesByID200ResponseDataInnerInverterInfo`
        """
        model = GetAccountDonglesByID200ResponseDataInnerInverterInfo()  # noqa: E501
        if include_optional:
            return GetAccountDonglesByID200ResponseDataInnerInverterInfo(
                battery_type = 'LITHIUM',
                battery = openapi_client.models.get_account_dongles_by_id_200_response_data_inner_inverter_info_battery.getAccountDonglesByID_200_response_data_inner_inverter_info_battery(
                    nominal_capacity = 110, 
                    nominal_voltage = 307, ),
                model = 'Gateway',
                max_charge_rate = 0
            )
        else:
            return GetAccountDonglesByID200ResponseDataInnerInverterInfo(
        )
        """

    def testGetAccountDonglesByID200ResponseDataInnerInverterInfo(self):
        """Test GetAccountDonglesByID200ResponseDataInnerInverterInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
