# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.evget_data_points200_response import EvgetDataPoints200Response  # noqa: E501

class TestEvgetDataPoints200Response(unittest.TestCase):
    """EvgetDataPoints200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EvgetDataPoints200Response:
        """Test EvgetDataPoints200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EvgetDataPoints200Response`
        """
        model = EvgetDataPoints200Response()  # noqa: E501
        if include_optional:
            return EvgetDataPoints200Response(
                data = [{"meter_id":0,"timestamp":"2023-06-01 08:00:00","measurements":[{"measurand":13,"value":1145,"unit":4},{"measurand":11,"value":50.2,"unit":null},{"measurand":21,"value":230.5,"unit":11}]}]
            )
        else:
            return EvgetDataPoints200Response(
        )
        """

    def testEvgetDataPoints200Response(self):
        """Test EvgetDataPoints200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
