# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_energy_flow_data_request import GetEnergyFlowDataRequest  # noqa: E501

class TestGetEnergyFlowDataRequest(unittest.TestCase):
    """GetEnergyFlowDataRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEnergyFlowDataRequest:
        """Test GetEnergyFlowDataRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEnergyFlowDataRequest`
        """
        model = GetEnergyFlowDataRequest()  # noqa: E501
        if include_optional:
            return GetEnergyFlowDataRequest(
                start_time = 2022-01-01,
                end_time = 2022-01-01,
                grouping = 0,
                types = [0,1,2,5]
            )
        else:
            return GetEnergyFlowDataRequest(
                start_time = 2022-01-01,
                end_time = 2022-01-01,
                grouping = 0,
        )
        """

    def testGetEnergyFlowDataRequest(self):
        """Test GetEnergyFlowDataRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
