# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.account_api import AccountApi  # noqa: E501


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_account_children_information_by_id(self) -> None:
        """Test case for get_account_children_information_by_id

        Get Account Children Information by ID  # noqa: E501
        """
        pass

    def test_get_account_dongles_by_id(self) -> None:
        """Test case for get_account_dongles_by_id

        Get Account Dongles by ID  # noqa: E501
        """
        pass

    def test_get_account_information_by_id(self) -> None:
        """Test case for get_account_information_by_id

        Get Account Information by ID  # noqa: E501
        """
        pass

    def test_get_account_information_by_username(self) -> None:
        """Test case for get_account_information_by_username

        Get Account Information by Username  # noqa: E501
        """
        pass

    def test_get_your_account_children_information(self) -> None:
        """Test case for get_your_account_children_information

        Get Your Account Children Information  # noqa: E501
        """
        pass

    def test_get_your_account_information(self) -> None:
        """Test case for get_your_account_information

        Get Your Account Information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
