# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_communication_device_information_by_serial_number200_response_data_inverter_info import GetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterInfo  # noqa: E501

class TestGetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterInfo(unittest.TestCase):
    """GetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterInfo:
        """Test GetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterInfo`
        """
        model = GetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterInfo()  # noqa: E501
        if include_optional:
            return GetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterInfo(
                battery_type = 'LEAD_ACID',
                battery = openapi_client.models.get_communication_device_information_by_serial_number_200_response_data_inverter_info_battery.getCommunicationDeviceInformationBySerialNumber_200_response_data_inverter_info_battery(
                    nominal_capacity = 165, 
                    nominal_voltage = 307, ),
                model = 'Commercial EMS',
                max_charge_rate = 2600
            )
        else:
            return GetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterInfo(
        )
        """

    def testGetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterInfo(self):
        """Test GetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
