# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_communication_device_information_by_serial_number200_response_data_inverter_connections_batteries_inner_capacity import GetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterConnectionsBatteriesInnerCapacity  # noqa: E501

class TestGetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterConnectionsBatteriesInnerCapacity(unittest.TestCase):
    """GetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterConnectionsBatteriesInnerCapacity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterConnectionsBatteriesInnerCapacity:
        """Test GetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterConnectionsBatteriesInnerCapacity
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterConnectionsBatteriesInnerCapacity`
        """
        model = GetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterConnectionsBatteriesInnerCapacity()  # noqa: E501
        if include_optional:
            return GetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterConnectionsBatteriesInnerCapacity(
                full = 180.75,
                design = 186
            )
        else:
            return GetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterConnectionsBatteriesInnerCapacity(
        )
        """

    def testGetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterConnectionsBatteriesInnerCapacity(self):
        """Test GetCommunicationDeviceInformationBySerialNumber200ResponseDataInverterConnectionsBatteriesInnerCapacity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
