# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_command_data200_response_data import GetCommandData200ResponseData  # noqa: E501

class TestGetCommandData200ResponseData(unittest.TestCase):
    """GetCommandData200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCommandData200ResponseData:
        """Test GetCommandData200ResponseData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCommandData200ResponseData`
        """
        model = GetCommandData200ResponseData()  # noqa: E501
        if include_optional:
            return GetCommandData200ResponseData(
                active = 'EcoPlus',
                available = ["Eco","EcoPlus","Boost"]
            )
        else:
            return GetCommandData200ResponseData(
        )
        """

    def testGetCommandData200ResponseData(self):
        """Test GetCommandData200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
