# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_ev_charger_by_uuid200_response import GetEVChargerByUUID200Response  # noqa: E501

class TestGetEVChargerByUUID200Response(unittest.TestCase):
    """GetEVChargerByUUID200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEVChargerByUUID200Response:
        """Test GetEVChargerByUUID200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEVChargerByUUID200Response`
        """
        model = GetEVChargerByUUID200Response()  # noqa: E501
        if include_optional:
            return GetEVChargerByUUID200Response(
                data = openapi_client.models.get_ev_charger_by_uuid_200_response_data.getEVChargerByUUID_200_response_data(
                    uuid = '00cd509e-27e9-4730-b64a-c4dd16234932', 
                    serial_number = '70458130637647', 
                    type = 'GivEnergy', 
                    alias = 'Garage', 
                    online = False, 
                    went_offline_at = '', 
                    status = 'Preparing', )
            )
        else:
            return GetEVChargerByUUID200Response(
        )
        """

    def testGetEVChargerByUUID200Response(self):
        """Test GetEVChargerByUUID200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
