# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_account_dongles_by_id200_response import GetAccountDonglesByID200Response  # noqa: E501

class TestGetAccountDonglesByID200Response(unittest.TestCase):
    """GetAccountDonglesByID200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAccountDonglesByID200Response:
        """Test GetAccountDonglesByID200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAccountDonglesByID200Response`
        """
        model = GetAccountDonglesByID200Response()  # noqa: E501
        if include_optional:
            return GetAccountDonglesByID200Response(
                data = [{"serial_number":"49niih5fqc","type":"GPRS","commission_date":"1997-02-03T00:08:03Z","inverter":{"serial":"WV6012O901","status":"LOST","last_online":"1998-11-29T17:03:36Z","last_updated":"1979-11-30T21:42:03Z","commission_date":"1979-07-25T07:42:16Z","info":{"battery_type":"LITHIUM","battery":{"nominal_capacity":110,"nominal_voltage":307},"model":"Gateway","max_charge_rate":0},"warranty":{"type":"Standard","expiry_date":"1984-07-25T07:42:16Z"},"firmware_version":{"ARM":420,"DSP":null},"connections":{"batteries":[{"serial":"ki1513g952","firmware_version":"22210","capacity":{"full":191.39,"design":186},"cell_count":16,"has_usb":false}]}}},{"serial_number":"36kfdj9sne","type":"GPRS","commission_date":"1982-07-05T08:34:41Z","inverter":{"serial":"CW1714G171","status":"UNKNOWN","last_online":"1999-08-14T02:29:33Z","last_updated":"1992-05-09T15:36:37Z","commission_date":"1975-07-17T07:21:58Z","info":{"battery_type":"LITHIUM","battery":{"nominal_capacity":165,"nominal_voltage":51.2},"model":"GIV-HY3.6","max_charge_rate":2600},"warranty":{"type":"Standard","expiry_date":"1980-07-17T07:21:58Z"},"firmware_version":{"ARM":420,"DSP":426},"connections":{"batteries":[{"serial":"bu9791j003","firmware_version":"59730","capacity":{"full":129.45,"design":160},"cell_count":16,"has_usb":false}]}}}]
            )
        else:
            return GetAccountDonglesByID200Response(
        )
        """

    def testGetAccountDonglesByID200Response(self):
        """Test GetAccountDonglesByID200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
