# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_charging_sessions200_response_data_inner import GetChargingSessions200ResponseDataInner  # noqa: E501

class TestGetChargingSessions200ResponseDataInner(unittest.TestCase):
    """GetChargingSessions200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetChargingSessions200ResponseDataInner:
        """Test GetChargingSessions200ResponseDataInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetChargingSessions200ResponseDataInner`
        """
        model = GetChargingSessions200ResponseDataInner()  # noqa: E501
        if include_optional:
            return GetChargingSessions200ResponseDataInner(
                started_by = '9f42852',
                meter_start = 933.4,
                started_at = '1999-12-30T22:08:56Z',
                stopped_by = '',
                meter_stop = '',
                stopped_at = '',
                stop_reason = ''
            )
        else:
            return GetChargingSessions200ResponseDataInner(
        )
        """

    def testGetChargingSessions200ResponseDataInner(self):
        """Test GetChargingSessions200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
