# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_account_children_information_by_id200_response_data_inner import GetAccountChildrenInformationByID200ResponseDataInner  # noqa: E501

class TestGetAccountChildrenInformationByID200ResponseDataInner(unittest.TestCase):
    """GetAccountChildrenInformationByID200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAccountChildrenInformationByID200ResponseDataInner:
        """Test GetAccountChildrenInformationByID200ResponseDataInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAccountChildrenInformationByID200ResponseDataInner`
        """
        model = GetAccountChildrenInformationByID200ResponseDataInner()  # noqa: E501
        if include_optional:
            return GetAccountChildrenInformationByID200ResponseDataInner(
                id = 15,
                name = 'rose.phoebe',
                role = 'OWNER',
                email = 'adams.scott@gmail.com',
                address = '80 Collins Land',
                postcode = 'MK9 2AD',
                country = 'MICRONESIA',
                telephone_number = '+44(0)316836121',
                timezone = 'GMT -4'
            )
        else:
            return GetAccountChildrenInformationByID200ResponseDataInner(
        )
        """

    def testGetAccountChildrenInformationByID200ResponseDataInner(self):
        """Test GetAccountChildrenInformationByID200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
