# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_latest_system_data200_response_data_solar import GetLatestSystemData200ResponseDataSolar  # noqa: E501

class TestGetLatestSystemData200ResponseDataSolar(unittest.TestCase):
    """GetLatestSystemData200ResponseDataSolar unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetLatestSystemData200ResponseDataSolar:
        """Test GetLatestSystemData200ResponseDataSolar
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetLatestSystemData200ResponseDataSolar`
        """
        model = GetLatestSystemData200ResponseDataSolar()  # noqa: E501
        if include_optional:
            return GetLatestSystemData200ResponseDataSolar(
                power = 3762,
                arrays = [{"array":1,"voltage":202.9,"current":788.7,"power":393},{"array":2,"voltage":626.5,"current":206.8,"power":2245}]
            )
        else:
            return GetLatestSystemData200ResponseDataSolar(
        )
        """

    def testGetLatestSystemData200ResponseDataSolar(self):
        """Test GetLatestSystemData200ResponseDataSolar"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
