# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.read_setting_multiple_request import ReadSettingMultipleRequest  # noqa: E501

class TestReadSettingMultipleRequest(unittest.TestCase):
    """ReadSettingMultipleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReadSettingMultipleRequest:
        """Test ReadSettingMultipleRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReadSettingMultipleRequest`
        """
        model = ReadSettingMultipleRequest()  # noqa: E501
        if include_optional:
            return ReadSettingMultipleRequest(
                inverter_serials = ["SERIAL_1","SERIAL_2"],
                setting_id = 17
            )
        else:
            return ReadSettingMultipleRequest(
                inverter_serials = ["SERIAL_1","SERIAL_2"],
                setting_id = 17,
        )
        """

    def testReadSettingMultipleRequest(self):
        """Test ReadSettingMultipleRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
