# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.evget_data_points200_response_data_inner_measurements_inner import EvgetDataPoints200ResponseDataInnerMeasurementsInner  # noqa: E501

class TestEvgetDataPoints200ResponseDataInnerMeasurementsInner(unittest.TestCase):
    """EvgetDataPoints200ResponseDataInnerMeasurementsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EvgetDataPoints200ResponseDataInnerMeasurementsInner:
        """Test EvgetDataPoints200ResponseDataInnerMeasurementsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EvgetDataPoints200ResponseDataInnerMeasurementsInner`
        """
        model = EvgetDataPoints200ResponseDataInnerMeasurementsInner()  # noqa: E501
        if include_optional:
            return EvgetDataPoints200ResponseDataInnerMeasurementsInner(
                measurand = 13,
                value = 1145.0,
                unit = 4
            )
        else:
            return EvgetDataPoints200ResponseDataInnerMeasurementsInner(
        )
        """

    def testEvgetDataPoints200ResponseDataInnerMeasurementsInner(self):
        """Test EvgetDataPoints200ResponseDataInnerMeasurementsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
