# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_charging_sessions200_response import GetChargingSessions200Response  # noqa: E501

class TestGetChargingSessions200Response(unittest.TestCase):
    """GetChargingSessions200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetChargingSessions200Response:
        """Test GetChargingSessions200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetChargingSessions200Response`
        """
        model = GetChargingSessions200Response()  # noqa: E501
        if include_optional:
            return GetChargingSessions200Response(
                data = [{"started_by":"9f42852","meter_start":933.4,"started_at":"1999-12-30T22:08:56Z","stopped_by":null,"meter_stop":null,"stopped_at":null,"stop_reason":null},{"started_by":"54bd6d5","meter_start":1423.7,"started_at":"1980-12-03T20:23:39Z","stopped_by":null,"meter_stop":null,"stopped_at":null,"stop_reason":null}]
            )
        else:
            return GetChargingSessions200Response(
        )
        """

    def testGetChargingSessions200Response(self):
        """Test GetChargingSessions200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
