# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.inverter_data_api import InverterDataApi  # noqa: E501


class TestInverterDataApi(unittest.TestCase):
    """InverterDataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InverterDataApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_data_points(self) -> None:
        """Test case for get_data_points

        Get Data Points  # noqa: E501
        """
        pass

    def test_get_events(self) -> None:
        """Test case for get_events

        Get Events  # noqa: E501
        """
        pass

    def test_get_latest_meter_data(self) -> None:
        """Test case for get_latest_meter_data

        Get Latest Meter Data  # noqa: E501
        """
        pass

    def test_get_latest_system_data(self) -> None:
        """Test case for get_latest_system_data

        Get Latest System Data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
