# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_account_dongles_by_id200_response_data_inner_inverter_firmware_version import GetAccountDonglesByID200ResponseDataInnerInverterFirmwareVersion  # noqa: E501

class TestGetAccountDonglesByID200ResponseDataInnerInverterFirmwareVersion(unittest.TestCase):
    """GetAccountDonglesByID200ResponseDataInnerInverterFirmwareVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAccountDonglesByID200ResponseDataInnerInverterFirmwareVersion:
        """Test GetAccountDonglesByID200ResponseDataInnerInverterFirmwareVersion
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAccountDonglesByID200ResponseDataInnerInverterFirmwareVersion`
        """
        model = GetAccountDonglesByID200ResponseDataInnerInverterFirmwareVersion()  # noqa: E501
        if include_optional:
            return GetAccountDonglesByID200ResponseDataInnerInverterFirmwareVersion(
                arm = 420,
                dsp = ''
            )
        else:
            return GetAccountDonglesByID200ResponseDataInnerInverterFirmwareVersion(
        )
        """

    def testGetAccountDonglesByID200ResponseDataInnerInverterFirmwareVersion(self):
        """Test GetAccountDonglesByID200ResponseDataInnerInverterFirmwareVersion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
