# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_data_points200_response_data_inner_today import GetDataPoints200ResponseDataInnerToday  # noqa: E501

class TestGetDataPoints200ResponseDataInnerToday(unittest.TestCase):
    """GetDataPoints200ResponseDataInnerToday unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDataPoints200ResponseDataInnerToday:
        """Test GetDataPoints200ResponseDataInnerToday
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDataPoints200ResponseDataInnerToday`
        """
        model = GetDataPoints200ResponseDataInnerToday()  # noqa: E501
        if include_optional:
            return GetDataPoints200ResponseDataInnerToday(
                solar = 4373.9,
                grid = openapi_client.models.get_data_points_200_response_data_inner_today_grid.getDataPoints_200_response_data_inner_today_grid(
                    import = 3168.4, 
                    export = 5384.4, ),
                battery = openapi_client.models.get_data_points_200_response_data_inner_today_battery.getDataPoints_200_response_data_inner_today_battery(
                    charge = 8691.3, 
                    discharge = 4350.4, ),
                consumption = 5673.7,
                ac_charge = 8021.5
            )
        else:
            return GetDataPoints200ResponseDataInnerToday(
        )
        """

    def testGetDataPoints200ResponseDataInnerToday(self):
        """Test GetDataPoints200ResponseDataInnerToday"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
