# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.read_setting200_response_data import ReadSetting200ResponseData  # noqa: E501

class TestReadSetting200ResponseData(unittest.TestCase):
    """ReadSetting200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReadSetting200ResponseData:
        """Test ReadSetting200ResponseData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReadSetting200ResponseData`
        """
        model = ReadSetting200ResponseData()  # noqa: E501
        if include_optional:
            return ReadSetting200ResponseData(
                value = True
            )
        else:
            return ReadSetting200ResponseData(
        )
        """

    def testReadSetting200ResponseData(self):
        """Test ReadSetting200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
