# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_account_information_by_username200_response import GetAccountInformationByUsername200Response  # noqa: E501

class TestGetAccountInformationByUsername200Response(unittest.TestCase):
    """GetAccountInformationByUsername200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAccountInformationByUsername200Response:
        """Test GetAccountInformationByUsername200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAccountInformationByUsername200Response`
        """
        model = GetAccountInformationByUsername200Response()  # noqa: E501
        if include_optional:
            return GetAccountInformationByUsername200Response(
                data = openapi_client.models.get_account_information_by_username_200_response_data.getAccountInformationByUsername_200_response_data(
                    id = 12, 
                    name = 'kelly44', 
                    role = 'ADMIN', 
                    email = 'hall.noah@gmail.co.uk', 
                    address = 'Flat 31
King Lake', 
                    postcode = 'AB11 5QE', 
                    country = 'SAINT_KITTS_AND_NEVIS', 
                    telephone_number = '(0064) 295 7686', 
                    timezone = 'GMT +4', )
            )
        else:
            return GetAccountInformationByUsername200Response(
        )
        """

    def testGetAccountInformationByUsername200Response(self):
        """Test GetAccountInformationByUsername200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
