# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.inverter_control_api import InverterControlApi  # noqa: E501


class TestInverterControlApi(unittest.TestCase):
    """InverterControlApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InverterControlApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_setting_presets(self) -> None:
        """Test case for get_setting_presets

        Get Setting Presets  # noqa: E501
        """
        pass

    def test_get_settings_list(self) -> None:
        """Test case for get_settings_list

        Get Settings List  # noqa: E501
        """
        pass

    def test_modify_preset(self) -> None:
        """Test case for modify_preset

        Modify Preset  # noqa: E501
        """
        pass

    def test_modify_setting(self) -> None:
        """Test case for modify_setting

        Modify Setting  # noqa: E501
        """
        pass

    def test_modify_setting_multiple(self) -> None:
        """Test case for modify_setting_multiple

        Modify Setting (Multiple)  # noqa: E501
        """
        pass

    def test_read_setting(self) -> None:
        """Test case for read_setting

        Read Setting  # noqa: E501
        """
        pass

    def test_read_setting_multiple(self) -> None:
        """Test case for read_setting_multiple

        Read Setting (Multiple)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
