# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, StrictInt, StrictStr, conlist
from openapi_client.models.evget_data_points200_response_data_inner_measurements_inner import EvgetDataPoints200ResponseDataInnerMeasurementsInner

class EvgetDataPoints200ResponseDataInner(BaseModel):
    """
    EvgetDataPoints200ResponseDataInner
    """
    meter_id: Optional[StrictInt] = None
    timestamp: Optional[StrictStr] = None
    measurements: Optional[conlist(EvgetDataPoints200ResponseDataInnerMeasurementsInner)] = None
    __properties = ["meter_id", "timestamp", "measurements"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EvgetDataPoints200ResponseDataInner:
        """Create an instance of EvgetDataPoints200ResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in measurements (list)
        _items = []
        if self.measurements:
            for _item in self.measurements:
                if _item:
                    _items.append(_item.to_dict())
            _dict['measurements'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EvgetDataPoints200ResponseDataInner:
        """Create an instance of EvgetDataPoints200ResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return EvgetDataPoints200ResponseDataInner.parse_obj(obj)

        _obj = EvgetDataPoints200ResponseDataInner.parse_obj({
            "meter_id": obj.get("meter_id"),
            "timestamp": obj.get("timestamp"),
            "measurements": [EvgetDataPoints200ResponseDataInnerMeasurementsInner.from_dict(_item) for _item in obj.get("measurements")] if obj.get("measurements") is not None else None
        })
        return _obj


