# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, conlist
from openapi_client.models.get_account_dongles_by_id200_response_data_inner_inverter_connections_batteries_inner import GetAccountDonglesByID200ResponseDataInnerInverterConnectionsBatteriesInner

class GetAccountDonglesByID200ResponseDataInnerInverterConnections(BaseModel):
    """
    GetAccountDonglesByID200ResponseDataInnerInverterConnections
    """
    batteries: Optional[conlist(GetAccountDonglesByID200ResponseDataInnerInverterConnectionsBatteriesInner)] = None
    __properties = ["batteries"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetAccountDonglesByID200ResponseDataInnerInverterConnections:
        """Create an instance of GetAccountDonglesByID200ResponseDataInnerInverterConnections from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in batteries (list)
        _items = []
        if self.batteries:
            for _item in self.batteries:
                if _item:
                    _items.append(_item.to_dict())
            _dict['batteries'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetAccountDonglesByID200ResponseDataInnerInverterConnections:
        """Create an instance of GetAccountDonglesByID200ResponseDataInnerInverterConnections from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GetAccountDonglesByID200ResponseDataInnerInverterConnections.parse_obj(obj)

        _obj = GetAccountDonglesByID200ResponseDataInnerInverterConnections.parse_obj({
            "batteries": [GetAccountDonglesByID200ResponseDataInnerInverterConnectionsBatteriesInner.from_dict(_item) for _item in obj.get("batteries")] if obj.get("batteries") is not None else None
        })
        return _obj


