# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr
from openapi_client.models.get_account_dongles_by_id200_response_data_inner_inverter import GetAccountDonglesByID200ResponseDataInnerInverter

class GetAccountDonglesByID200ResponseDataInner(BaseModel):
    """
    GetAccountDonglesByID200ResponseDataInner
    """
    serial_number: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    commission_date: Optional[StrictStr] = None
    inverter: Optional[GetAccountDonglesByID200ResponseDataInnerInverter] = None
    __properties = ["serial_number", "type", "commission_date", "inverter"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetAccountDonglesByID200ResponseDataInner:
        """Create an instance of GetAccountDonglesByID200ResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of inverter
        if self.inverter:
            _dict['inverter'] = self.inverter.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetAccountDonglesByID200ResponseDataInner:
        """Create an instance of GetAccountDonglesByID200ResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GetAccountDonglesByID200ResponseDataInner.parse_obj(obj)

        _obj = GetAccountDonglesByID200ResponseDataInner.parse_obj({
            "serial_number": obj.get("serial_number"),
            "type": obj.get("type"),
            "commission_date": obj.get("commission_date"),
            "inverter": GetAccountDonglesByID200ResponseDataInnerInverter.from_dict(obj.get("inverter")) if obj.get("inverter") is not None else None
        })
        return _obj


