# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr

class GetEventsRequest(BaseModel):
    """
    GetEventsRequest
    """
    cleared: Optional[StrictBool] = None
    start: Optional[StrictStr] = Field(None, description="Must be a valid date. Must be a date before <code>tomorrow</code>.")
    end: Optional[StrictStr] = Field(None, description="Must be a valid date. Must be a date after <code>start</code>.")
    __properties = ["cleared", "start", "end"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetEventsRequest:
        """Create an instance of GetEventsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetEventsRequest:
        """Create an instance of GetEventsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GetEventsRequest.parse_obj(obj)

        _obj = GetEventsRequest.parse_obj({
            "cleared": obj.get("cleared"),
            "start": obj.get("start"),
            "end": obj.get("end")
        })
        return _obj


