# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictBool, StrictStr
from openapi_client.models.get_data_points200_response_data_inner_power import GetDataPoints200ResponseDataInnerPower
from openapi_client.models.get_data_points200_response_data_inner_today import GetDataPoints200ResponseDataInnerToday
from openapi_client.models.get_data_points200_response_data_inner_total import GetDataPoints200ResponseDataInnerTotal

class GetDataPoints200ResponseDataInner(BaseModel):
    """
    GetDataPoints200ResponseDataInner
    """
    time: Optional[StrictStr] = None
    power: Optional[GetDataPoints200ResponseDataInnerPower] = None
    today: Optional[GetDataPoints200ResponseDataInnerToday] = None
    total: Optional[GetDataPoints200ResponseDataInnerTotal] = None
    is_metered: Optional[StrictBool] = None
    __properties = ["time", "power", "today", "total", "is_metered"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetDataPoints200ResponseDataInner:
        """Create an instance of GetDataPoints200ResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of power
        if self.power:
            _dict['power'] = self.power.to_dict()
        # override the default output from pydantic by calling `to_dict()` of today
        if self.today:
            _dict['today'] = self.today.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total
        if self.total:
            _dict['total'] = self.total.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetDataPoints200ResponseDataInner:
        """Create an instance of GetDataPoints200ResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GetDataPoints200ResponseDataInner.parse_obj(obj)

        _obj = GetDataPoints200ResponseDataInner.parse_obj({
            "time": obj.get("time"),
            "power": GetDataPoints200ResponseDataInnerPower.from_dict(obj.get("power")) if obj.get("power") is not None else None,
            "today": GetDataPoints200ResponseDataInnerToday.from_dict(obj.get("today")) if obj.get("today") is not None else None,
            "total": GetDataPoints200ResponseDataInnerTotal.from_dict(obj.get("total")) if obj.get("total") is not None else None,
            "is_metered": obj.get("is_metered")
        })
        return _obj


