# coding: utf-8

"""
    GivEnergy API Documentation (v1.14.0)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError

from typing_extensions import Annotated
from pydantic import Field, StrictInt, StrictStr

from typing import Optional

from openapi_client.models.create_smart_device_data_point200_response import CreateSmartDeviceDataPoint200Response
from openapi_client.models.create_smart_device_data_point_request import CreateSmartDeviceDataPointRequest
from openapi_client.models.get_smart_device_by_id200_response import GetSmartDeviceByID200Response
from openapi_client.models.get_smart_device_data_points_by_id200_response import GetSmartDeviceDataPointsByID200Response

from openapi_client.api_client import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class SmartDeviceApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def create_smart_device_data_point(self, smart_device_uuid : Annotated[StrictStr, Field(..., description="The UUID of the smartDevice.")], create_smart_device_data_point_request : CreateSmartDeviceDataPointRequest, authorization : Optional[StrictStr] = None, **kwargs) -> CreateSmartDeviceDataPoint200Response:  # noqa: E501
        """Create Smart Device Data Point  # noqa: E501

        Store a data point against a smart device  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_smart_device_data_point(smart_device_uuid, create_smart_device_data_point_request, authorization, async_req=True)
        >>> result = thread.get()

        :param smart_device_uuid: The UUID of the smartDevice. (required)
        :type smart_device_uuid: str
        :param create_smart_device_data_point_request: (required)
        :type create_smart_device_data_point_request: CreateSmartDeviceDataPointRequest
        :param authorization: 
        :type authorization: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: CreateSmartDeviceDataPoint200Response
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the create_smart_device_data_point_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.create_smart_device_data_point_with_http_info(smart_device_uuid, create_smart_device_data_point_request, authorization, **kwargs)  # noqa: E501

    @validate_arguments
    def create_smart_device_data_point_with_http_info(self, smart_device_uuid : Annotated[StrictStr, Field(..., description="The UUID of the smartDevice.")], create_smart_device_data_point_request : CreateSmartDeviceDataPointRequest, authorization : Optional[StrictStr] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Create Smart Device Data Point  # noqa: E501

        Store a data point against a smart device  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_smart_device_data_point_with_http_info(smart_device_uuid, create_smart_device_data_point_request, authorization, async_req=True)
        >>> result = thread.get()

        :param smart_device_uuid: The UUID of the smartDevice. (required)
        :type smart_device_uuid: str
        :param create_smart_device_data_point_request: (required)
        :type create_smart_device_data_point_request: CreateSmartDeviceDataPointRequest
        :param authorization: 
        :type authorization: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(CreateSmartDeviceDataPoint200Response, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'smart_device_uuid',
            'create_smart_device_data_point_request',
            'authorization'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_smart_device_data_point" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['smart_device_uuid']:
            _path_params['smartDevice_uuid'] = _params['smart_device_uuid']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        if _params['authorization']:
            _header_params['Authorization'] = _params['authorization']

        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['create_smart_device_data_point_request'] is not None:
            _body_params = _params['create_smart_device_data_point_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['default']  # noqa: E501

        _response_types_map = {
            '200': "CreateSmartDeviceDataPoint200Response",
        }

        return self.api_client.call_api(
            '/smart-device/{smartDevice_uuid}/data', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def get_smart_device_by_id(self, smart_device_uuid : Annotated[StrictStr, Field(..., description="The UUID of the smartDevice.")], authorization : Optional[StrictStr] = None, **kwargs) -> GetSmartDeviceByID200Response:  # noqa: E501
        """Get Smart Device by ID  # noqa: E501

        Get a smart device's information  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_smart_device_by_id(smart_device_uuid, authorization, async_req=True)
        >>> result = thread.get()

        :param smart_device_uuid: The UUID of the smartDevice. (required)
        :type smart_device_uuid: str
        :param authorization: 
        :type authorization: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: GetSmartDeviceByID200Response
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_smart_device_by_id_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.get_smart_device_by_id_with_http_info(smart_device_uuid, authorization, **kwargs)  # noqa: E501

    @validate_arguments
    def get_smart_device_by_id_with_http_info(self, smart_device_uuid : Annotated[StrictStr, Field(..., description="The UUID of the smartDevice.")], authorization : Optional[StrictStr] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Get Smart Device by ID  # noqa: E501

        Get a smart device's information  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_smart_device_by_id_with_http_info(smart_device_uuid, authorization, async_req=True)
        >>> result = thread.get()

        :param smart_device_uuid: The UUID of the smartDevice. (required)
        :type smart_device_uuid: str
        :param authorization: 
        :type authorization: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(GetSmartDeviceByID200Response, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'smart_device_uuid',
            'authorization'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_smart_device_by_id" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['smart_device_uuid']:
            _path_params['smartDevice_uuid'] = _params['smart_device_uuid']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        if _params['authorization']:
            _header_params['Authorization'] = _params['authorization']

        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['default']  # noqa: E501

        _response_types_map = {
            '200': "GetSmartDeviceByID200Response",
        }

        return self.api_client.call_api(
            '/smart-device/{smartDevice_uuid}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def get_smart_device_data_points_by_id(self, smart_device_uuid : Annotated[StrictStr, Field(..., description="The UUID of the smartDevice.")], page : Annotated[Optional[StrictInt], Field(description="Page number to return")] = None, page_size : Annotated[Optional[StrictInt], Field(description="Number of items to return in a page. Defaults to 15")] = None, authorization : Optional[StrictStr] = None, **kwargs) -> GetSmartDeviceDataPointsByID200Response:  # noqa: E501
        """Get Smart Device Data Points by ID  # noqa: E501

        Get a list of a smart device's data points  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_smart_device_data_points_by_id(smart_device_uuid, page, page_size, authorization, async_req=True)
        >>> result = thread.get()

        :param smart_device_uuid: The UUID of the smartDevice. (required)
        :type smart_device_uuid: str
        :param page: Page number to return
        :type page: int
        :param page_size: Number of items to return in a page. Defaults to 15
        :type page_size: int
        :param authorization: 
        :type authorization: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: GetSmartDeviceDataPointsByID200Response
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_smart_device_data_points_by_id_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.get_smart_device_data_points_by_id_with_http_info(smart_device_uuid, page, page_size, authorization, **kwargs)  # noqa: E501

    @validate_arguments
    def get_smart_device_data_points_by_id_with_http_info(self, smart_device_uuid : Annotated[StrictStr, Field(..., description="The UUID of the smartDevice.")], page : Annotated[Optional[StrictInt], Field(description="Page number to return")] = None, page_size : Annotated[Optional[StrictInt], Field(description="Number of items to return in a page. Defaults to 15")] = None, authorization : Optional[StrictStr] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Get Smart Device Data Points by ID  # noqa: E501

        Get a list of a smart device's data points  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_smart_device_data_points_by_id_with_http_info(smart_device_uuid, page, page_size, authorization, async_req=True)
        >>> result = thread.get()

        :param smart_device_uuid: The UUID of the smartDevice. (required)
        :type smart_device_uuid: str
        :param page: Page number to return
        :type page: int
        :param page_size: Number of items to return in a page. Defaults to 15
        :type page_size: int
        :param authorization: 
        :type authorization: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(GetSmartDeviceDataPointsByID200Response, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'smart_device_uuid',
            'page',
            'page_size',
            'authorization'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_smart_device_data_points_by_id" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['smart_device_uuid']:
            _path_params['smartDevice_uuid'] = _params['smart_device_uuid']


        # process the query parameters
        _query_params = []
        if _params.get('page') is not None:  # noqa: E501
            _query_params.append(('page', _params['page']))

        if _params.get('page_size') is not None:  # noqa: E501
            _query_params.append(('pageSize', _params['page_size']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        if _params['authorization']:
            _header_params['Authorization'] = _params['authorization']

        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['default']  # noqa: E501

        _response_types_map = {
            '200': "GetSmartDeviceDataPointsByID200Response",
        }

        return self.api_client.call_api(
            '/smart-device/{smartDevice_uuid}/data', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
